### ISSUE TITLE
Debate watch parties homepage CTA

### ISSUE THREAD

**Issue by coinbasemar** [Stand-With-Crypto/swc-web#1006]
Let's update the hero image on the homepage to link to a new presidential debate watch parties page.

This page will show all presidential debates by city and allow the user to click out to RSVP on the respective events pages. Longer term, this will serve as an events page, but for now we should only show upcoming watch parties. 

Link to Figma: https://www.figma.com/design/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?node-id=4193-745

Link to spreadsheet of events: https://docs.google.com/spreadsheets/d/11H-ZGpVVALzpQehMIMQJ7TumTPjr3A8aRc4-HbY2OT0/edit?usp=sharing

**Comment by travisbloom-cb** [comment]
Lets make the page /events/cnn-debate
