### ISSUE TITLE
Add NFT Mint to all UserActions

### ISSUE THREAD

**Issue by lucasrmp-cb** [Stand-With-Crypto/swc-web#101]

**Comment by coinbasemar** [comment]
@axelmarko-cb there was some conversation about this being on hold until gas fees dropped – did we decide to go ahead and give users NFTs for all actions?

**Comment by coinbasemar** [comment]
@axelmarko-cb Is there a PRD or any write up on this?

**Comment by coinbasemar** [comment]
Users should also be able to click into their NFT to see details: 

Large version of the NFT
Title
Description
Potentially other information, e.g. how many other holders of the NFT are there.

**Comment by axelmarko-cb** [comment]
@coinbasemar not yet but it's in the backlog
