### ISSUE TITLE
Investigate on how to add comments to prisma queries

### ISSUE THREAD

**Issue by twistershark** [Stand-With-Crypto/swc-web#1040]
We need to find a solution on how to add key value pair comments in prisma queries to be able to track which queries are having bad performance.

Possible solutions:
- Prisma extensions: We may be able to create a custom prisma extension to add this comments
- Create a custom `prismaClient` that would accept comments as well: We'll probably need to investigate `prisma's` source code to use this approach.

**Comment by twistershark** [comment]
Related issues:
- https://github.com/prisma/prisma/issues/10746
- https://github.com/prisma/prisma/issues/13360

**Comment by lucasrmp-cb** [comment]
Abandoned feature by prisma
