### ISSUE TITLE
Map interaction updates

### ISSUE THREAD

**Issue by coinbasemar** [Stand-With-Crypto/swc-web#1096]
Let's make the follow updates to the map to more accurately reflect our activity levels:

1. The map should only have 5 actions to start with
2. Every 2 seconds a new action should appear on the screen
3. We should cycle through the most recent 30 actions
4. Don't have more than 10 actions on the map at a time, once a new action is added the oldest action should disappear
5. After getting to the last 10 actions, the actions should stay on until newer actions come and replace

**Comment by olavoparno** [comment]
After review, change the following items:

- Adjust map description "See the most recent actions our community has taken to safeguard the future of crypto in America"
- Test out 20 actions on the map rather than 10
