### ISSUE TITLE
Expand on user analytics to diff between email and phone sign ups

### ISSUE THREAD

**Issue by olavoparno** [Stand-With-Crypto/swc-web#1176]
@travisbloom-cb if you want to add your notes on it

**Comment by travisbloom-cb** [comment]
we need similar logic to [this](https://github.com/Stand-With-Crypto/swc-web/blob/main/src/utils/server/thirdweb/onLogin.ts#L351) for phone number

**Comment by olavoparno** [comment]
We now have `Has Embedded Wallet Phone Number` for the User Logged In event
