### ISSUE TITLE
Change Success Screen message

### ISSUE THREAD

**Issue by twistershark** [Stand-With-Crypto/swc-web#1362]
When users are logged in using query params, they won't receive NFTs until they log in using their wallet. Instead of showing that the user received an NFT after completing as action while being logged in in this state, we want to show the default message

**Comment by twistershark** [comment]
This issue is currently on hold until election day. Instead of using the custom message, we are displaying a single description about voter information, as shown in the screenshot below.

![Image](https://github.com/user-attachments/assets/a0cca630-2854-438c-b170-87b2f3d1e1a6)

**Comment by lucasrmp-cb** [comment]
@twistershark what's the status on this? Does this issue still make sense?

**Comment by twistershark** [comment]
@lucasrmp-cb This is still an issue if I'm not mistaken because users coming from CB app will not receive the NFT until they manually login on SWC, but on our current success screens, we show that the user has received an NFT even though they are not logged in with thirdweb. 

I think that we should tweak the message just for clarity
