### ISSUE TITLE
Redesign vote page

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#1460]
https://www.figma.com/design/NfKwbY2nWgWOogRlKhS7bB/Voter-Journey?node-id=1022-3693

**Comment by coinbasemar** [comment]
We're updating our Voter Guide page to be more engaging. We should make the following updates:

1. Update the countdown UI as shown in Figma
2. Update the copy on the header and body
3. Update action card UI as shown in Figma

Link to designs: https://www.figma.com/design/NfKwbY2nWgWOogRlKhS7bB/Voter-Journey?node-id=1022-3693
