### ISSUE TITLE
Election night live results

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#1461]
Figma: https://www.figma.com/design/NfKwbY2nWgWOogRlKhS7bB/Voter-Journey?node-id=1009-482&node-type=canvas&t=G3ACpakIWObctN8m-11

**Comment by coinbasemar** [comment]
We're repurposing our Key Races page to show live election data on election night. We should add the following:

1. A "Live election results" button in the header (remove key races tab in header in favor of this)
2. A Trump vs. Kamala progress bar that shows how many votes each party is receiving
3. A crypto election map that shows the number of pro-crypto candidates being elected in each state, with the ability to click in and view each state's page
4. An address bar for viewing elections in a user's area
5. Updated cards for the 13 critical elections that we show on the key races page
6. An upsell to complete the "I Voted" flow

This work also includes updating the state and race level pages with relevant changes.

Link to Figma (WIP): https://www.figma.com/design/NfKwbY2nWgWOogRlKhS7bB/Voter-Journey?node-id=1009-482

**Comment by travisbloom-cb** [comment]
- Add report that says any matching/lack of matching anomalies that get returned from decision desk/DTSI
