### ISSUE TITLE
Retail mini-dApps Donation Flow - Support creation of web3 Commerce charges

### ISSUE THREAD

**Issue by benson-budiman-cb** [Stand-With-Crypto/swc-web#222]
https://docs.cloud.coinbase.com/commerce-onchain/docs/accepting-crypto

~~SwC V1 used this API, so I assume that there are Coinbase Commerce donation flows that don't directly go through the website.~~

~~NOTE: Coinbase Commerce recently undergone a significant API changes (_e.g._ from "v1" to "v2", and now, any new Coinbase Commerce accounts will be part of the new v2 API, but any already existing accounts will still behave with v1 API (for now).~~

Our production Coinbase Commerce account is now on "v2" Commerce (a.k.a. "web3" Commerce). We already have an integration with the "web3" Commerce API's "create charge" endpoint [here](https://github.com/Stand-With-Crypto/swc-web/blob/main/src/utils/server/coinbaseCommerce/createCharge.ts), but we probably need to make modifications to match the specs of Retail mini-dApps donation flow (_e.g._ the screens for this donation flow include hardcoded donation values like $5, $10, $20, etc., so we should be passing those values when creating the charge).

**Comment by travisbloom-cb** [comment]
Update, we need to use v2 API now moving forward.
