### ISSUE TITLE
Commerce Donations V2 migration - Hard cut off by April

### ISSUE THREAD

**Issue by vicfrolov-cb** [Stand-With-Crypto/swc-web#294]
Commerce Donations is deprecating V1 donations, and will have a hard cutoff on either April 1 or April 15 (https://coinbase.slack.com/archives/C05H8D0HZLN/p1707751566519319?thread_ts=1707506519.988589&cid=C05H8D0HZLN)

DRI on Commerce team for support: Kevin Smith

**Comment by travisbloom-cb** [comment]
@benson-budiman-cb closing this out. LMK if it needs to be re-opened.
