### ISSUE TITLE
Make column headers in politician table sticky

### ISSUE THREAD

**Issue by axelmarko-cb** [Stand-With-Crypto/swc-web#450]
Column headers should be sticky (same as filters)

![Image](https://github.com/Stand-With-Crypto/swc-web/assets/156484301/d62c240a-99b1-405f-b017-4856d7c2c35c)

also adjust zindex for menu ![Image](https://github.com/user-attachments/assets/f664da20-de44-465e-8cad-b22d651605c1)

**Comment by olavoparno** [comment]
handled on https://github.com/Stand-With-Crypto/swc-web/issues/815
