### ISSUE TITLE
Persist filters for politician table by updating the query params

### ISSUE THREAD

**Issue by axelmarko-cb** [Stand-With-Crypto/swc-web#453]
Example: When a user selects a filter and clicks on a politician profile from the table and then goes back to the table they should see the filtered table view

**Comment by travisbloom-cb** [comment]
we need to change filters from being tracked via state to being tracked via [query params](https://github.com/Stand-With-Crypto/swc-web/blob/611-update-add-position-text-box-message/src/hooks/useQueryParamState.ts#L9)

**Comment by lucasrmp-cb** [comment]
We can have both, serializing and deserializing the state from the query params

**Comment by olavoparno** [comment]
handled on https://github.com/Stand-With-Crypto/swc-web/issues/815
