### ISSUE TITLE
Skip address input screen in call flow when user authenticated and/or has provided address before

### ISSUE THREAD

**Issue by axelmarko-cb** [Stand-With-Crypto/swc-web#454]
For call flow when the user is authenticated and has provided an address, instead of just auto-filling, can we skip this step altogether.

**Comment by travisbloom-cb** [comment]
We should ensure this ticket resolve #456 as well

**Comment by axelmarko-cb** [comment]
@coinbasemar to drop in new designs once available

**Comment by coinbasemar** [comment]
designs here: https://www.figma.com/file/E6n5yUZiG5buSj0MzoaEr8/standwithcrypto.org?type=design&node-id=14653-62296&mode=design&t=twgNtJ8u1bXDYYVn-4
