### ISSUE TITLE
[Mobile] Minimize menu before opening bottom tray

### ISSUE THREAD

**Issue by axelmarko-cb** [Stand-With-Crypto/swc-web#455]
When opening the profile tray on mobile, can we first minimize the menu before opening the bottom tray on top of it?

![Image](https://github.com/Stand-With-Crypto/swc-web/assets/156484301/5b1731f6-fb79-499f-94ee-7b22037153d2)

**Comment by travisbloom-cb** [comment]
Suprisingly difficult to achieve. Moving this back to needs prioritization for now
