### ISSUE TITLE
Clicking on "Call" button for your rep should deep link into last step of call flow

### ISSUE THREAD

**Issue by axelmarko-cb** [Stand-With-Crypto/swc-web#456]
When user clicks on "Call" CTA button on the "/politicians" page, they shouldn't have to select their rep and instead go directly to the final step in the flow

![Image](https://github.com/Stand-With-Crypto/swc-web/assets/156484301/029878ef-293c-474c-8bb0-80a2ab38ee1c)

**Comment by travisbloom-cb** [comment]
Will be resolved by #454
