### ISSUE TITLE
In the logged in state, the main CTA flashes Join the fight and then visibly switches to Finish your profile

### ISSUE THREAD

**Issue by jimobrien-cb** [Stand-With-Crypto/swc-web#463]

**Comment by travisbloom-cb** [comment]
Not sure the right strategy to solve this :( there are two options - we don’t show any text until the client JavaScript loads or we optimize for the unauthenticated state and have the flash for logged in users. Open to switching but there will be some trade offs either way. We either want the SEO approach or the app-centric approach
