### ISSUE TITLE
Clicking on username, the text under View profile has inconsistent spacing

### ISSUE THREAD

**Issue by jimobrien-cb** [Stand-With-Crypto/swc-web#471]

**Comment by travisbloom-cb** [comment]
@coinbasemar to provide guidance first

**Comment by coinbasemar** [comment]
Not sure what this is referring to

**Comment by travisbloom-cb** [comment]
@coinbasemar does this spacing make sense to you? if so can you close this ticket



![Image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/6c42509b-6064-4d18-9912-d211e5d7825d)
