### ISSUE TITLE
Address field on Politicians page keeps resetting

### ISSUE THREAD

**Issue by jimobrien-cb** [Stand-With-Crypto/swc-web#473]

**Comment by travisbloom-cb** [comment]
Closed until we can reproduce

**Comment by axelmarko-cb** [comment]
@travisbloom-cb @jimobrien-cb not sure if this is context for the original ticket but when unauthenticated on the /politicians page, I see the following:

1. Type in address to find rep
2. Click anywhere else on the page (or even on a politician in the table) and the address is reset

**Comment by travisbloom-cb** [comment]
@axelmarko-cb closing. Lmk if you can reproduce.
