### ISSUE TITLE
Update default ordering for table when filters are selected

### ISSUE THREAD

**Issue by axelmarko-cb** [Stand-With-Crypto/swc-web#475]
Should order by default: 

1. By grade
2. By last name (within the same grade)

**Comment by axelmarko-cb** [comment]
@travisbloom-cb can you confirm if this is done already? The specific feedback didn't take into account that there are 'promoted' politicians on the landing page

**Comment by travisbloom-cb** [comment]
@axelmarko-cb we sort by promoted positioning, then fall back to stance score now. Closing this out.

**Comment by axelmarko-cb** [comment]
@travisbloom-cb I think it would make more sense to have:

1) Promoted
2) Grade
3) Last name

Right now the sorting looks pretty random to the user as we don't expose the actual underlying score that leads to a specific grade.
