### ISSUE TITLE
Typing in verification code on thirdweb auth causes weird jank on mobile

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#519]
See video

https://github.com/Stand-With-Crypto/swc-web/assets/153657370/208347af-d675-4231-b0fb-ec6e023eee89

**Comment by travisbloom-cb** [comment]
Lets time box this to 2 days before regrouping if we can't figure it out

**Comment by paulovictor-cb** [comment]
This issue is being resolved by Thirdweb team. Current progress is discussed in this tread: https://coinbasedevelopers.slack.com/archives/C05KZUAHM2L/p1715974246691869

**Comment by twistershark** [comment]
Closing because this is not an issue anymore after the V5 upgrade
