### ISSUE TITLE
NFT success screen flickers

### ISSUE THREAD

**Issue by axelmarko-cb** [Stand-With-Crypto/swc-web#545]
Success screen flickers twice. Steps to reproduce:

1. Navigate to event deep link
2. Type in email and confirm code
3. Observe screen flickering

https://github.com/Stand-With-Crypto/swc-web/assets/156484301/1e17c911-b776-4fe0-8865-3526bb1d418d

**Comment by kl-cb** [comment]
This will affect all action flows accessed via deeplink since we refresh the page when user logs in so it will re-render the dialog.
