### ISSUE TITLE
Implement queuing mechanism for NFT airdrops

### ISSUE THREAD

**Issue by benson-budiman-cb** [Stand-With-Crypto/swc-web#552]
Every airdrop burns through some of our airdropping Base ETH funds, but because we are initializing a new transaction for each individual user instead of bundling the airdrops into a single transaction via `multiclaim`, we are burning through the funds much faster than in v1.

Wallet 1: https://basescan.org/address/0xc2A6116e9a1f9aDD1Bb87EEF308f216Bb0304c38
Wallet 2: https://basescan.org/address/0x4B0e6c1f66cA950B22e9Eaa8f075F0944a705B03

Do time-based bundling (_e.g._ just attempt multi-claim every 2-3 minutes with dynamic bundle size)

**Comment by travisbloom-cb** [comment]
Closing this out after discussing with TW team. Seems it wont help our gas fee usage that much
