### ISSUE TITLE
Add e2e tests for mint NFT flow

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#569]
https://testing.standwithcrypto.org/action/nft-mint

Open technical questions:
- How can we mock out the Thirdweb auth flow?
-- naive approach would be to have a bunch of conditionals that only work in cypress environment

**Comment by olavoparno** [comment]
We're now using LocalWallets for the cypress environment https://blog.thirdweb.com/guides/how-to-use-local-wallets/
