### ISSUE TITLE
Change layout of "I'm a Voter" modal

### ISSUE THREAD

**Issue by axelmarko-cb** [Stand-With-Crypto/swc-web#583]
Change layout to have the image above the text, left-aligned. Instead of having the image and text in 2 columns. 

@coinbasemar to provide design

**Comment by coinbasemar** [comment]
https://www.figma.com/file/6KDFbJaCzTCqV9mG9U4Nb8/voter-regis?type=design&node-id=151-36055&mode=design&t=pmQ3LMZCFS9wujNX-4
