### ISSUE TITLE
Users should be able to click on their NFTs to see details

### ISSUE THREAD

**Issue by axelmarko-cb** [Stand-With-Crypto/swc-web#585]
Users should see following details:

- Large version of the NFT
- Title
- Description

Potentially other information, e.g. how many other holders of the NFT are there.

**Comment by coinbasemar** [comment]
@axelmarko-cb Is this something we're still prioritizing? I'm assuming this means when a user clicks on one of the NFTs on their profile we'd show an L2 with the information above.

**Comment by axelmarko-cb** [comment]
Yeah some sort of modal or L2. 

Not highest priority for now but something we should still build out at some point, especially as we start to add more NFTs for actions.
