### ISSUE TITLE
Donation not showing up on leaderboard

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#598]
two issues:
- Commerce analytics event [appear](https://mixpanel.com/project/3191713/view/3702825/app/insights#6aCddjnVZ2XF) to not being correctly associated with a user 
- None of our new donations are linked to emails/wallets/sessions

I think these are related and might have to do with how we match users from the payload

**Comment by masonleenaugh** [comment]
gatesonchain.eth donated $69.42 on march 6 around 1:20 PM CST
it showed up on the event feed (see below)

![image](https://github.com/Stand-With-Crypto/swc-web/assets/7013596/c9b235c0-28aa-4650-a5a1-65daad8c2eab)

but this tx did not show up on the leaderboard 

here is the tx on basescan: https://basescan.org/tx/0xc162baaad793e4304b1259141533f153f4114d8c7f95f2201813be5b58ca8392

**Comment by masonleenaugh** [comment]
Seems like everything is working great.

**Comment by benson-budiman-cb** [comment]
@masonleenaugh do you know if the user has logged-in with their email address or their personal crypto wallet? I ask because I still see an Anonymous user on the leaderboard that matches the results of my findings.
