### ISSUE TITLE
No commerce payments are being associated with users in mixpanel

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#615]
See [this graph](https://mixpanel.com/s/2C6g3x). I think there might be a bug with how we find the associated user [here](https://github.com/Stand-With-Crypto/swc-web/blob/contribute-updates/src/app/api/internal/commerce-webhook/route.ts#L35). Also, we should use the ["track User action created"](https://github.com/Stand-With-Crypto/swc-web/blob/contribute-updates/src/utils/server/serverAnalytics/serverAnalytics.ts#L96) logic for this.

**Comment by benson-budiman-cb** [comment]
![image](https://github.com/Stand-With-Crypto/swc-web/assets/135282747/a257b1c6-081b-498f-b121-ff7148f83521)

![image](https://github.com/Stand-With-Crypto/swc-web/assets/135282747/505a5e01-fe35-4727-ba52-da4d588de14b)

User actions of type `DONATION` should now appear, and the "Coinbase Commerce Payment" event has been renamed to "Coinbase Commerce webhook event received" for clarity-sake.
