### ISSUE TITLE
Location-specific pages

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#638]
### Other Dependencies:
- [x] #634 
- [ ] #330 
### Maybe Dependencies?
- [ ] #636 
- [ ] #639

**Comment by coinbasemar** [comment]
Designs: https://www.figma.com/file/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?type=design&node-id=643-22365&mode=design
