### ISSUE TITLE
Show whether a position is for or against crypto

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#639]
Similar to how we do it in [DTSI](https://www.dotheysupportit.com/people/cynthia---lummis/crypto#stance-1191a33f-6568-4f2b-83cd-40c526d698f7)

**Comment by coinbasemar** [comment]
Designs: https://www.figma.com/file/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?type=design&node-id=847-12035&mode=design&t=DayAbRgSONgpaTFf-4
