### ISSUE TITLE
Bills pages

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#643]

**Comment by coinbasemar** [comment]
Designs: https://www.figma.com/file/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?type=design&node-id=29-1394&mode=design

**Comment by travisbloom-cb** [comment]
This work should also include adding a link to the bill page when we see a [DTSI stance referencing a bill](https://github.com/Stand-With-Crypto/swc-web/blob/642-support-contacting-multiple-politicians-across-the-site-instead-of-just-congressperson/src/components/app/dtsiStanceDetails/dtsiStanceDetailsBillRelationship.tsx#L16)

**Comment by travisbloom-cb** [comment]
We'll also want to replace the bills list [on this page](https://www.standwithcrypto.org/resources) with the API

**Comment by travisbloom-cb** [comment]
@travisbloom-cb to ship API that supports this page before @eduardopicolo-cb starts work
