### ISSUE TITLE
Denormalize total donations per user and deprecate expensive query usage

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#660]
We have all sorts of performance issues associated with [this query](https://github.com/Stand-With-Crypto/swc-web/blob/main/src/data/aggregations/getSumDonationsByUser.ts#L33). This ticket includes the work needed to add a new `totalDonationAmountUsd` to the user table, and plug in the logic needed to backfill/keep up to date/use.

There are multiple PRs that we'll need:

- One to add the new db column
- One that proactively updates it in the actions that impact it moving forward (donation webhook and donation mint action) and updates the merge logic appropriately.
- One to add a cron job that audits all the fields for all the users and performs any necessary sums - simply iterate through each user, and for each user, get their NFT mints and donations, then sum that up (or maybe combine with above)
- One to update the current getSumDonationsByUser logic to use this new field instead

**Comment by travisbloom-cb** [comment]
Other options:
- figure out how to index this properly to be performant
- Create a [view](https://www.prisma.io/docs/orm/prisma-schema/data-model/views)

**Comment by benson-budiman-cb** [comment]
_Update 2024-03-21_

Doing some digging on the "other options" - I am pretty sure we cannot really optimize the complex query:

- We already have initialized the indexes used by the query, so nothing more we can add their
- MySQL supports updatable views but not materialized views
  - We can only realize improved query performances from materialized views
  - We can mock materialized views by recreating them as tables, but that is a hacky solution and requires careful management in regards to the timing and performance impact of refreshing the materialized table.
- Other rewrites of the query do not improve query performance 

I think we should do the denormalize solution.

**Comment by travisbloom-cb** [comment]
Have a cron job that audits the field for all users
