### ISSUE TITLE
Add mocks to Coinbase Commerce

### ISSUE THREAD

**Issue by lucasrmp-cb** [Stand-With-Crypto/swc-web#709]

**Comment by travisbloom-cb** [comment]
@lucasrmp-cb can you add more context about why we need this?

**Comment by lucasrmp-cb** [comment]
The idea here is mock this requests so we don't break calls like [this one](https://github.com/Stand-With-Crypto/swc-web/blob/279f44034bd47a476334d43620b34b67b6de71ff/src/components/app/pageDonate/donateButton.tsx#L22) because the OS contributor won't have credentials for coinbase commerce. That's also true for capitol canary calls

**Comment by lucasrmp-cb** [comment]
We'll work with synthetic tests for those cases, it makes this request unnecessary
