### ISSUE TITLE
Post-action chaining (with focus on SMS)

### ISSUE THREAD

**Issue by coinbasemar** [Stand-With-Crypto/swc-web#725]
When a user completes an action on SWC, we should show their advocacy progress and suggested next actions to take based on priority. 

Designs: https://www.figma.com/file/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?type=design&node-id=962-3129&mode=design&t=DayAbRgSONgpaTFf-4

**Comment by coinbasemar** [comment]
Designs: https://www.figma.com/file/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?type=design&node-id=962-3129&mode=design&t=DayAbRgSONgpaTFf-4

**Comment by travisbloom-cb** [comment]
dup of #678
