### ISSUE TITLE
Register to vote farcaster frame

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#739]

**Comment by benson-budiman-cb** [comment]
Links for testing the development frame:
- https://debugger.framesjs.org/?url=https%3A%2F%2Fswc-web-git-tay-frame-stand-with-crypto.vercel.app%2Fframes%2Fregister-to-vote
- https://warpcast.com/~/developers/frames?url=https%3A%2F%2Fswc-web-git-tay-frame-stand-with-crypto.vercel.app%2Fframes%2Fregister-to-vote
