### ISSUE TITLE
Update primary font from Raleway to Satoshi

### ISSUE THREAD

**Issue by coinbasemar** [Stand-With-Crypto/swc-web#747]
Our primary font used for headers and display titles should be changed from Raleway to Satoshi.

Link to font: https://www.fontshare.com/fonts/satoshi

Link to Figma: https://www.figma.com/file/ZGYKkf5yHXoS2jadfbB4NM/SWC-Design-System?type=design&node-id=5-2&mode=design&t=MJ0eFkjrletXS9Gi-4

**Comment by travisbloom-cb** [comment]
https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
