### ISSUE TITLE
Migrate to v5 of Thirdweb SDK

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#773]

**Comment by jnsdls** [comment]
I'd like to take this, will try to get around to it this weekend and open a PR :)

**Comment by twistershark** [comment]
TDD: https://docs.google.com/document/d/1Jx-m4BPV2D5tGAPh_D1PQORfxAImZ8Paof5Ij9rCL-E/edit?usp=sharing
