### ISSUE TITLE
Pizza Day Activation

### ISSUE THREAD

**Issue by axelmarko-cb** [Stand-With-Crypto/swc-web#798]
See details:

- [PRD](https://docs.google.com/document/d/1COkY3M29qShFSA5pkHVjEsqdtvC4SaaART7ub1tPXvw/edit)
- [Designs](https://www.figma.com/file/ZkzUkPXQbHZLFeHjdONJUq/Pizza-Day?type=design&node-id=7-17177&mode=design&t=eqReNhhSiognkNRQ-11)

**Comment by coinbasemar** [comment]
Link to Pizza Day NFT: https://drive.google.com/file/d/1g3kuXaxwpri0Vvq-c7wzpl2fs3eTyfU5/view?usp=sharing
