### ISSUE TITLE
Trigger revalidatePath for API endpoints doesn't work

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#811]
When we hit the [DTSI webhook](https://github.com/Stand-With-Crypto/swc-web/blob/re-enable-donations/src/app/api/internal/dtsi-updated-slugs-webhook/route.ts#L47) the dtsiAllPeople is not getting refreshed. the [revalidate flag](https://github.com/Stand-With-Crypto/swc-web/blob/re-enable-donations/src/app/api/public/dtsi/all-people/route.ts#L9) does trigger the refresh on the specified interval.

**Comment by travisbloom-cb** [comment]
Timeboxed to one day

**Comment by travisbloom-cb** [comment]
Additional details. It appears `https://standwithcrypto.org/api/public/dtsi/by-geography/usa/NY/26` has been returning cached data for days without updating. If i tweak the url to `https://standwithcrypto.org/api/public/dtsi/by-geography/usa/ny/26` it returns the correct data.

**Comment by travisbloom-cb** [comment]
timeboxed to a day of initial investigation

**Comment by twistershark** [comment]
@travisbloom-cb from what I've seen, I'm not completely sure if we can invalidate the api route using `revalidatePath`, but one possible solution for this would be to use `revalidateTag`. It works like the query key in React Query where you can invalidate a specific key or every key that contains a certain string. 

My approach here would be to add a new optional arg to fetchReq to accept this tags prop and then call invalidateTag directly in `dtsi-updated-slugs-webhook`
