### ISSUE TITLE
Prevent the politician row from navigating when clicking while holding CMD or CTRL

### ISSUE THREAD

**Issue by ghost** [Stand-With-Crypto/swc-web#815]
When you try to open a politician's page in a new tab using CMD or CTRL, even though the new tab is opened, the table row is also capturing this click and navigating the current tab to the politician's page.

https://github.com/Stand-With-Crypto/swc-web/assets/165944245/01f0a4a8-4bd2-4436-8394-02d08fd064bc

**Comment by travisbloom-cb** [comment]
We'll want to ensure this also continues to support the entire row being clickable. (We may want to see if we can somehow wrap the content in a a tag instead of relying on onClick events)

**Comment by olavoparno** [comment]
linked issues:

https://github.com/Stand-With-Crypto/swc-web/issues/450
https://github.com/Stand-With-Crypto/swc-web/issues/453
