### ISSUE TITLE
SWC OCS activation - Voter Attestation

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#826]
Specs here: https://docs.google.com/document/d/1iLHF2__vwUDbh6RreHvqkI6RjjCGz-RYR-5IP4Y5QaY/edit

**Comment by coinbasemar** [comment]
Figma: https://www.figma.com/design/8Qd0r8Zn9XqjcLWW1HW1Nh/OCS-Voter-Attestation?node-id=6-391

**Comment by coinbasemar** [comment]
@travisbloom-cb @axelmarko-cb Final designs: https://www.figma.com/design/8Qd0r8Zn9XqjcLWW1HW1Nh/OCS-Voter-Attestation?node-id=6-391
