### ISSUE TITLE
Deal with error spikes caused by SWC email campaigns

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#848]
Every time SWC team sends emails out to advocates we see a spike in error rates on the site. See this [mixpanel view](https://mixpanel.com/s/4HlVE). Looking in sentry to correlate the error pages to actual exceptions yields examples [like this](https://stand-with-crypto.sentry.io/issues/5037833904/?environment=production&project=4506490717470720&query=is%3Aunresolved+timesSeen%3A%3E%3D10&referrer=issue-stream&statsPeriod=30d&stream_index=0). The error message is not helpful, but if you scroll down to the breadcrumbs you see we log the message "antifingerprint not defined yet. will try and handle event after its ready".

Investigating this error leads to [this insight](https://github.com/getsentry/sentry-javascript/issues/9143#issuecomment-2002664796). It appear whats happening is that a percentage of advocates are using outlook, and their outlook app is scanning SWC when the email arrives.

We need to:
- figure out how ignore these kinds of email bot scans in Sentry
- figure out how to ignore these kinds of events in mixpanel

OR

- figure out to get the error to not occur (which seems unlikely)

**Comment by matheusmendes-cb** [comment]
According to this [message](https://github.com/getsentry/sentry-javascript/issues/3440#issuecomment-1233146122) and the [docs from sentry](https://docs.sentry.io/platforms/javascript/configuration/filtering/#using--1), we should be able to ignore those errors on Sentry by just adding the following regex: `/Non-Error promise rejection captured with value: Object Not Found/` to `ignoreErrors` inside `Sentry.init`.

This regex will filter out any string that contains the substring `Non-Error promise rejection captured with value: Object Not Found`, that is the immutable substring of the error message.

**Comment by travisbloom-cb** [comment]
> According to this [message](https://github.com/getsentry/sentry-javascript/issues/3440#issuecomment-1233146122) and the [docs from sentry](https://docs.sentry.io/platforms/javascript/configuration/filtering/#using--1), we should be able to ignore those errors on Sentry by just adding the following regex: `/Non-Error promise rejection captured with value: Object Not Found/` to `ignoreErrors` inside `Sentry.init`.
> 
> This regex will filter out any string that contains the substring `Non-Error promise rejection captured with value: Object Not Found`, that is the immutable substring of the error message.

Yup, we do this [here](https://github.com/Stand-With-Crypto/swc-web/blob/798/pizza-day-activation/sentry.client.config.ts#L74), now just need to figure out how to ignore in mixpanel

**Comment by paulovictor-cb** [comment]
@travisbloom-cb The reason that the errors spiked again was that I added a new type named route in the filters for google places api. 

This new type is required for other countries like Brazil, but they cause issues on US. 

One possible solution would be to do this filtering manually from the google places api results. If it is possible to know which country the user is from based on the search, we can filter the results more restrictively in US but allow others types in other countries.

What do you think?

**Comment by mhamendes** [comment]
@olavoparno
