### ISSUE TITLE
Nav bar updates

### ISSUE THREAD

**Issue by coinbasemar** [Stand-With-Crypto/swc-web#870]
Let's update our nav bar in order to support the scale of the pages we're adding to SWC.

Figma: https://www.figma.com/design/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?node-id=3086-708

**Comment by coinbasemar** [comment]
@travisbloom-cb this one is good to go https://www.figma.com/design/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?node-id=3086-708

**Comment by travisbloom-cb** [comment]
@axelmarko-cb to see if we should add this to the sprint

**Comment by axelmarko-cb** [comment]
See thread on this here: https://www.figma.com/design/gVjeMzqORPBEI0EarwIymi?node-id=50-6484#898220811 

Will be completed as part of the Events page work
