### ISSUE TITLE
Make it easy for people to add crypto addresses to existing account coming from coinbase

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#872]
https://coinbase.slack.com/archives/C05M2BJQNSE/p1715800069666009?thread_ts=1715797740.109489&cid=C05M2BJQNSE

**Comment by axelmarko-cb** [comment]
@travisbloom-cb is this still relevant? The slack message has been deleted

**Comment by travisbloom-cb** [comment]
we can prob close. There's def a conversation we need to have about how users coming from verified partners can leverage onchain functionality when they open the browser in a non-onchain website
