### ISSUE TITLE
Show phone number to call on desktop call flow

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#887]
![Image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/bbc04676-f4dd-43e1-87be-c120dc7b1290)

**Comment by coinbasemar** [comment]
@travisbloom-cb let's actually use this design here and let's also update the body copy on desktop to say:

Call the number below and then click “Call complete” when finished.

Link to Figma: https://www.figma.com/design/E6n5yUZiG5buSj0MzoaEr8/standwithcrypto.org?node-id=14994-21686&t=3UxVAaHaaLzQkYg4-4

![Screenshot 2024-05-20 at 11 18 18 AM](https://github.com/Stand-With-Crypto/swc-web/assets/161389643/ced81369-b4a8-4da8-b3d8-3b314e9af3f0)
