### ISSUE TITLE
Audit planetscale for missing indexes

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#900]
Seeing elevated number of queries taking >1s. We should audit [insights](https://app.planetscale.com/stand-with-crypto/swc-web/main/insights?p99.9=1&p99=1) to see what queries are taking a long time and make sure we've got the right indexes

**Comment by travisbloom-cb** [comment]
Let's time box this to 3 days and regroup

**Comment by twistershark** [comment]
This issue is blocked by #1040

**Comment by lucasrmp-cb** [comment]
Adding scope to this:

Let's audit queries with lots of reads and a few number of indexes (excluding aggregations) and check if we can add indexes to any columns to increase performance.

Let's focus on queries we use on login here
