### ISSUE TITLE
Reskin email flow for "thanks for voting" FIT21

### ISSUE THREAD

**Issue by lucasrmp-cb** [Stand-With-Crypto/swc-web#907]
This envolves a change in designs, copy and conditionally showing different messages for representatives that voted yes/no/abstain for FIT21

**Comment by travisbloom-cb** [comment]
![Image](https://github.com/Stand-With-Crypto/swc-web/assets/153657370/62eaa9f7-2f21-4a88-8453-a6f3f9ce4c28)
