### ISSUE TITLE
Add back nextjs-toploader

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#91]
Waiting on https://github.com/TheSGJ/nextjs-toploader/issues/66

**Comment by tomcru** [comment]
You are welcome to use https://github.com/tomcru/holy-loader in the meantime, it's a drop-in replacement without this bug.

**Comment by AndlerRL** [comment]
Is this still an issue? A couple of months ago I had the same issue with version `1.6.4`

**Comment by travisbloom-cb** [comment]
@tomcru would welcome a PR :) we're trying to encourage more open source contributions!
