### ISSUE TITLE
tweak UX of actions to account for multiple campaigns existing

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#928]
Email campaigns that have occurred:
- FIT21 campaign back in 2023
- FIT21 Campaign in 2024
- FIT21 Thank you campaign

Future stuff
- FIT21 senate vote
- White house email

**Comment by coinbasemar** [comment]
Final designs: https://www.figma.com/design/vockMtDZ6U6hEnAVbmxoC4/Action-cards?node-id=1-18
