### ISSUE TITLE
Live map of activations

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#929]

**Comment by coinbasemar** [comment]
Context:

Link to PRD: https://docs.google.com/document/d/1XHm3YqTh5wdgUrQvq5Fg3hqhbMCHOqjtQFz1Ucnq55M/edit?usp=sharing&resourcekey=0-Nn3qVK2SicPHvMe8FpoHjw

We're creating an interactive map of the United States that shows all sign ups to Stand With Crypto. This will be displayed on monitors at live events and eventually shown on the SWC site.

On the map, dots should appear on a state whenever a new member joins from there. There should be clusters for the 3-5 largest cities where we have users. We should also show a live advocate counter at the top.

Here's a link to the Figma as well as references for the animations:

Figma: https://www.figma.com/design/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?node-id=3808-560

Map hover animation: https://interactivegeomaps.com/feature/heatmap/

Advocate counter: https://codepen.io/phillyc/pen/nwMEeZ

cc: @travisbloom-cb

**Comment by travisbloom-cb** [comment]
To reduce scope here:
- Lets use the existing `AnimatedNumericOdometer` component for counter
- Lets see if there's any react friendly maps that we can achieve a similar effect with off the shelf.
