### ISSUE TITLE
Support thirdweb sign in with phone number

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#930]
**FIRST: Confirm whether we need to upgrade to v5 to use this functionality (in that case this is blocked by #773 )**

Thirdweb now supports sign in w/ phone number - https://thirdweb.com/dashboard/connect/playground. We'd like to migrate from showcasing email as an option to showing phone number. A few eng notes to consider:

- Our [schema](https://github.com/Stand-With-Crypto/swc-web/blob/main/prisma/schema.prisma#L91) assumes the "primary identifiers" of a user are their email, wallet address, or session id. We'll need to figure out any adjustments we'd like to make to account for phone numbers being a primary identifier (prob need an [embedded wallet phone number](https://github.com/Stand-With-Crypto/swc-web/blob/main/prisma/schema.prisma#L232))
- Verify w/ thirdweb they have similar APIs we can leverage to [get the phone number](https://github.com/Stand-With-Crypto/swc-web/blob/main/src/utils/server/thirdweb/fetchEmbeddedWalletMetadataFromThirdweb.ts#L22)
- Figure out how this impacts [our merge logic](https://github.com/Stand-With-Crypto/swc-web/blob/main/src/utils/server/thirdweb/onLogin.ts#L185)
- Modify the profile form step to account for the fact we have phone number already and need email for instances where that is the case
- Modify the initial sign up page to include sms opt in legalese

**Comment by travisbloom-cb** [comment]
Please sync w/ Travis to review schema changes after documenting

**Comment by travisbloom-cb** [comment]
Verified w/ TW team we dont need to upgrade and we can leverage [these docs](https://portal.thirdweb.com/connect/in-app-wallet/how-to/get-in-app-wallet-details-on-server) for fetching the phone number

**Comment by olavoparno** [comment]
After a brief discussion we came to the following flow:

- User logs in either using **thirdweb** phone number sign in or not, and if there's a match with the same phone number that's been verified (reply to SMS), then we match accounts, otherwise we create anew. 
- If user logs in using using **thirdweb** phone number sign in, we do not ask for phone number input on the **update your profile form**.

**Comment by olavoparno** [comment]
- [ ] update thirdweb deps (v4 still)
- [ ] add phone number as thirdweb sign in options
- [ ] test out and modify sign in scenarios such as new account sign in, merge with existing accounts, etc

**Comment by olavoparno** [comment]
Comments:

- We don't ask the user to OPT IN to SMS again if the number's changed.
- If user signs in with their email, adds phone number and verify it, account will be merged if signed in with phone number next time.
- If user signs in with their phone and adds email, account will not be merged if signed in with email next time.

**Comment by olavoparno** [comment]
https://github.com/Stand-With-Crypto/swc-web/pull/1054

**Comment by olavoparno** [comment]
- Add phone number sign in with experiments

**Comment by olavoparno** [comment]
- [Bug bash doc](https://docs.google.com/document/d/18FtyDMgmljkqZjVVhc1ShBFgveDt67wF1Q7BTMNl4gY/edit#heading=h.6w0f913kyj2w)
