### ISSUE TITLE
CNN Email Campaign

### ISSUE THREAD

**Issue by coinbasemar** [Stand-With-Crypto/swc-web#959]
Context:

We're creating an action on Stand With Crypto to prompt people to email CNN and ask them to include crypto as a presidential debate topic. We can leverage our email flow that we already have in place, but this should be a new action separate from our current email flow. They will both exist concurrently. 

The copy is still WIP (contact @axelmarko-cb for details) but the designs are good to go. This should be treated like any other action card, so it will show up on the homepage as well as the profile page.

Link to Figma: https://www.figma.com/design/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?node-id=3811-2010

**Comment by travisbloom-cb** [comment]
We'll want to extend the UserActionEmailRecipient model to include an optional emailAddress string field, we'll need a new campaign for this, and we'll need to modify our logic to allow for multiple email campaigns to be running concurrently.
