### ISSUE TITLE
Decrease success modal width

### ISSUE THREAD

**Issue by eduardopicolo-cb** [Stand-With-Crypto/swc-web#993]
Less whitespace on the sides for the UserActionFormSuccessScreen.

![image](https://github.com/Stand-With-Crypto/swc-web/assets/167582510/3f830004-376f-4bb7-a0e4-fc053176e26a)

Currently, the `dialogContentStyles` has `width: 100%` for desktop and every `UserActionForm` dialog have a max-width set to `max-w-3xl`.

**Comment by travisbloom-cb** [comment]
@coinbasemar is this still an issue?
