### ISSUE TITLE
Key races page V2

### ISSUE THREAD

**Issue by coinbasemar** [Stand-With-Crypto/swc-web#999]
Let's update the races on the key races page to be organized by state. Layout should include:

1. State shield icon
2. State name
3. Race
4. Candidates
5. CTA to view race

Link to Figma: https://www.figma.com/design/MWzmEAYQC1NYZiD4BG0FlI/V2-Fast-Follows?node-id=4196-2768

Mock shown below, using fake candidate & race data:

<img width="1068" alt="Screenshot 2024-06-21 at 12 35 20 PM" src="https://github.com/Stand-With-Crypto/swc-web/assets/161389643/5313fce5-6785-4fbe-bef6-47c6cb05acfc">

**Comment by travisbloom-cb** [comment]
Image assets for all states https://drive.google.com/drive/folders/18ZnwgWLvkeMYcRyGHpjZJrzYUn5-1AB8
